### ISSUE TITLE
Android `No static method create` error after updating from 0.3.1 to 0.4.0 

### ISSUE THREAD

**Issue by sebastinto** [tensorflow/tflite-support#824]
After updating the `org.tensorflow:tensorflow-lite-support` dependency from `0.3.1` to `0.4.0`, both `.tflite` models used in an Android project cannot be initialized. The project uses Android Studio ML Binding.

When either model is initialized using `MyModel.newInstance(context, Model.Options.Builder().<some options>` (so initialization is similar to the code snippet in step 2 of the tensorflow doc [here](https://www.tensorflow.org/lite/inference_with_metadata/codegen#acceleration)) the app crashes with this error:

```
java.lang.NoSuchMethodError: No static method create(Ljava/nio/ByteBuffer;Lorg/tensorflow/lite/InterpreterApi$Options;)Lorg/tensorflow/lite/InterpreterApi; in class Lorg/tensorflow/lite/InterpreterApi; or its super classes (declaration of 'org.tensorflow.lite.InterpreterApi' appears in /data/app/com.mydomain==/base.apk!classes21.dex)
        at org.tensorflow.lite.support.model.Model.createModel(Model.java:217)
        at org.tensorflow.lite.support.model.Model.createModel(Model.java:181)
        at com.mydomain.ml.MyModel.<init>(MyModel.java:24)
        at com.mydomain.ml.MyModel.newInstance(MyModel.java:30)
        at com.mydomain.models.MyModel.<init>(MyModel.kt:25)
```

Other tflite dependencies used:

`org.tensorflow:tensorflow-lite-metadata:0.4.0`
`org.tensorflow:tensorflow-lite-gpu:2.9.0`
`org.tensorflow:tensorflow-lite:2.8.0`

Has any API changed? Should the models be re-exported with config changes? Any pointer as to where to look or how to fix the issue would be greatly appreciated, thanks!

**Comment by lu-wang-g** [comment]
Android Studio ML binding is not upgraded to tflite-support 0.4 yet. You should continue using tflite-support 0.3.1.

**Comment by sebastinto** [comment]
> Android Studio ML binding is not upgraded to tflite-support 0.4 yet. You should continue using tflite-support 0.3.1.

Oh, that's good to know. Is the upgrade planned? Thanks!

**Comment by lu-wang-g** [comment]
I'm afraid not in the near future... But if you need any upgrade or are interested in any particular feature, let us know.

**Comment by sebastinto** [comment]
> I'm afraid not in the near future... But if you need any upgrade or are interested in any particular feature, let us know.

Cool, I was just curious but I'll make sure to let you know if we encounter a road block! Thanks for the help!
